services:
  db:
    image: postgres:16
    container_name: capstone_db
    restart: always
    environment:
      POSTGRES_USER: capstone_user
      POSTGRES_PASSWORD: capstone_pass
      POSTGRES_DB: capstone_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
